### ISSUE TITLE
ActionMenus are too small!

### ISSUE THREAD

**Issue by stefanoverna** [frontapp/front-ui-kit#173]
This line https://github.com/frontapp/front-ui-kit/blob/d8a8951a1ab9d882cb6dd9220366c052d3a1aad7/src/components/popover/reposition.tsx#L63 forces `<ActionMenu>` to have a maximum width of 160px, regardless of its `width` prop.

**Comment by stefanoverna** [comment]
Actually I'm not really sure that the problem lies in that line, but the issue is there 😕

**Comment by stefanoverna** [comment]
Actually, the problem is here:

https://github.com/frontapp/front-ui-kit/blob/main/src/elements/dropdown/dropdown.tsx#L201

the `minWidth` prop of the `Dropdown` component is not passed down

**Comment by mwoodhousemckenzie** [comment]
:wave: Thanks for raising this issue. This is by design, action menus are suppose to be a smaller menu to do quick actions from. If you are needing a larger menu, you should use the `Dropdown` component ([Ref](https://frontapp.github.io/front-ui-kit/?path=/docs/elements-dropdown--basic)) and build out a custom dropdown.

But as you noted, it does seem like we are not truly supporting the `minWidth` parameter. I have fixed this in https://github.com/frontapp/front-ui-kit/pull/177 and now when changing the size of the `ActionMenu` it does grow bigger.
